### ISSUE TITLE
Change font to alternate-gothic-no-1-d for headlines in the forms and korolev for the labels

### ISSUE THREAD

**Issue by jonathan-wiens** [berlin-international-community-church/church-database#105]

**Comment by giubueno** [comment]
It seems that this font is proprietary (Adobe) but you can use it if you have an Adobe account (apparently).

https://fonts.adobe.com/fonts/alternate-gothic

**Comment by jonathan-wiens** [comment]
Not required any longer. We just capitalize everything which will change the look a bit
