### ISSUE TITLE
Remove unneeded filters

### ISSUE THREAD

**Issue by jonathan-wiens** [berlin-international-community-church/church-database#123]
Remove the following filter criteria

* Family
* Address
* Attendees
* Option answers
* Question answers
* Leaders
* Reset*
* Remeber created at
* Current sign in at
* Last sign in at
* Current sign in IP
* Last sign in IP
* Confirmed at
* Confirmation sent at
* Unconfirmed email
* Failed attempts
* Unlock tokens
* Locked at
* Discarded at

**Comment by adetunjiakintundeakinde** [comment]
This filter exists on the member page

**Comment by giubueno** [comment]
I think it was already done.
