### ISSUE TITLE
Change title of form to the title of the questionnaire

### ISSUE THREAD

**Issue by jonathan-wiens** [berlin-international-community-church/church-database#161]
Currently the HTML title element says "church" hard coded. Let's change it to the name of the form, ie. for "https://church-database.herokuapp.com/events/87/register" it should be "Vision Sunday (February 16, 11:00, 13:00, 16:00) - LET US KNOW YOU ARE COMING."

**Comment by giubueno** [comment]
https://github.com/berlin-international-community-church/church-database/pull/162
