### ISSUE TITLE
Create Events

### ISSUE THREAD

**Issue by rafaelbiriba** [berlin-international-community-church/church-database#21]

**Comment by jonathan-wiens** [comment]
Further fields for EventInstance

- available dates: list of dates when the event will happen (e.g. 6 dates for a Community Group season)
- status: string (e.g. draft, public, private, archived)
- contact1: member (that gets an e-mail upon submission)
- contact2: member (that gets an e-mail upon submission) 
- contact3: member (that gets an e-mail upon submission)

?? New table "form"
-  JSON? Database tables? Should be user-friendly long term
??

API requirements (from front end)
- POST API to store users sign up (action->event_submission), that includes the ID of the event instance and the form data (e.g. JSON)

**Comment by giubueno** [comment]
@jonathan-wiens let's discuss this again, please.

**Comment by giubueno** [comment]
Done.
