### ISSUE TITLE
Fix new_member e-mail

### ISSUE THREAD

**Issue by jonathan-wiens** [berlin-international-community-church/church-database#87]
This email doesn't list all the options from an answer (e.g. with multiple checkboxes selected)

**Comment by thiagopio** [comment]
Could you please show me when it happens?

**Comment by jonathan-wiens** [comment]
When filling out a form like this:

<img width="1066" alt="form" src="https://user-images.githubusercontent.com/1003491/58583858-3ab0b100-8255-11e9-80bc-2156cf754b95.png">

The email that is sent out looks like this:

<img width="479" alt="email" src="https://user-images.githubusercontent.com/1003491/58583888-47cda000-8255-11e9-99da-66108cd48dd3.png">

The email is missing the information that the person checked the boxes for Water Baptism & Growing My Faith
